# Generated by Django 2.1.3 on 2018-11-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_recruitjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='site_app.Job'),
        ),
        migrations.AlterField(
            model_name='recruitjob',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='site_app.Recruit'),
        ),
    ]
